name: 'Performance Monitoring'
on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://adventures:polaris@adventures.polaris-test.run/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true

      - name: Run ls
        run: ls
