name: 'Performance Monitoring'
on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://adventures:polaris@adventures.polaris-test.run/
            https://adventures:polaris@adventures.polaris-test.run/adventures/by-state-arizona/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true

      - name: Save Lighthouse Report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: ./lighthouse-results.zip
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: lighthouse-report
          # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: ./lighthouse-results.zip
